name: Node CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: npm install, build, and test
      run: |
        npm install doctest standard --save-dev
        # TODO: Remove the next line when #539 is fixed.
        rm  Dynamic-Programming/MinimumCostPath.js Graphs/PrimMST.js
        # npx doctest **/*.js
        npx standard
        npm ci
        npm run build --if-present
        # TODO: Remove the next line when #539 is fixed.
        rm  Linear-Algebra/test/test.js String/LevenshteinDistance.test.js
        npm test
      env:
        CI: true
    - run: npx doctest Backtracking/*.js
    - run: npx doctest Cache/*.js
    - run: npx doctest Ciphers/*.js
    - run: npx doctest Conversions/*.js
    - run: npx doctest Data-Structures/*/*.js
    - run: npx doctest Dynamic-Programming/*.js
    - run: npx doctest Graphs/*.js
    - run: npx doctest Hashes/*.js
    - run: npx doctest Linear-Algebra/*.js
    - run: npx doctest Maths/*.js
    - run: npx doctest Navigation/*.js
    - run: npx doctest Project-Euler/*.js
    - run: npx doctest Recursive/*.js
    - run: npx doctest Search/*.js
    - run: npx doctest Sorts/*.js
    - run: npx doctest String/*.js
    - run: npx doctest Timing-Functions/*.js
    - run: npx doctest Trees/*.js
    - run: npx doctest Web-Programming/*.js
