name: Node CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: npm install, build, and test
      run: |
        npm install doctest standard --save-dev
        # TODO: Remove the next line when #539 is fixed.
        rm  Javascript/Dynamic-Programming/MinimumCostPath.js
        npx doctest **/*.js
        npx standard
        npm ci
        npm run build --if-present
        # TODO: Remove the next line when #539 is fixed.
        rm  Linear-Algebra/test/test.js String/LevenshteinDistance.test.js
        npm test
      env:
        CI: true
